name: metrics
excludes:
  - node_modules
services:
  node:
    type: node:10
    command: yarn run start
    build:
      - yarn
events:
  pre-push:
    - node: yarn test
tooling:
  push:
    cmd: git push
    description: Push new code into QA
    service: appserver
  yarn:
    service: node
  test:
    cmd: yarn test
    service: node
