name: metrics
type: nodejs:6.10

dependencies:
  nodejs:
    pm2: "^2.0.0"
    grunt-cli: "latest"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start server.js --no-daemon"
  locations:
    "/public":
      passthru: false
      root: "public"
      allow: true
      rules:
        '\.png$':
          allow: true
          expires: -1

mounts:
  "/run": "shared:files/run"
  "/.platformsh": "shared:files/.platformsh"

disk: 512

hooks:
  build: |
    npm install
    curl -sS https://platform.sh/cli/installer | php
    echo "updates:" >> /app/.platformsh/config.yaml
    echo "check: false" >> /app/.platformsh/config.yaml
