language: node_js
node_js:
  - '10'
services:
  - docker

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb https://files.lando.dev/lando-stable.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

script:
  - lando npm install
  - lando start
  - lando grunt test
