https://stats.devwithlando.io/:
  type: redirect
  to: https://{default}/
https://metrics.devwithlando.io/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
https://metrics.lndo.io/:
  type: redirect
  to: https://{default}/
https://stats.lndo.io/:
  type: redirect
  to: https://{default}/
https://stats.lando.dev/:
  type: redirect
  to: https://{default}/
https://stats-v2.kalabox.io/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
