http://metrics.lndo.io/:
  type: redirect
  to: http://{default}/
http://stats.lndo.io/:
  type: redirect
  to: http://{default}/
http://stats.devwithlando.io/:
  type: redirect
  to: http://{default}/
http://stats-v2.kalabox.io/:
  type: redirect
  to: http://{default}/
http://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: metrics:http
